{{ config(materialized='table') }}

-- ============================================================================
-- dim_location
-- ----------------------------------------------------------------------------
-- Conformed location dimension. Shared by both fact tables.
--
-- Grain: one row per unique combination of
--        (borough, zip_code, neighborhood, council_district).
--
-- Built by unioning the location attributes from both staging models, then
-- deduplicating. This guarantees every location_key referenced by either
-- fact table has a matching row here.
--
-- Surrogate key (location_key) is generated by row_number() over the
-- deduplicated set. Same input always produces the same key as long as
-- the underlying data is stable.
-- ============================================================================

with locations_311 as (

    select distinct
        borough,
        zip_code,
        neighborhood,
        council_district
    from {{ ref('stg_311') }}

),

locations_ace as (

    select distinct
        borough,
        zip_code,
        neighborhood,
        council_district
    from {{ ref('stg_ace') }}

),

unioned as (

    select * from locations_311
    union distinct
    select * from locations_ace

)

select
    -- surrogate key: dense, sequential integer
    row_number() over (
        order by borough, zip_code, neighborhood, council_district
    ) as location_key,

    borough,
    zip_code,
    neighborhood,
    council_district

from unioned
